# Site settings
title: Deep Curiosity
description: "My personal blog"
url: 
author:
  name: "Awais Rauf"
  email: "iawaisrauf@gmail.com"
  url: ""
  

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
mathjax: true
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/


# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: https-awaisrauf-github-io-deepcuriosity
