# Site settings
title: Deep Curiosity
description: "My personal blog"
avatar: https://i.pinimg.com/originals/96/49/0b/96490b41c31620203288c84a071026c9.png
url: 
author:
  name: "Muhammad Awais"
  email: "iawaisrauf@gmail.com"
  url: ""
  

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/


# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
